version: "3"
services:
  mongo:
      image: mongo:4
      expose:
        - 27017
      ports:
        - 27017:27017
  rabbitmq:
    image: "rabbitmq:3"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
